02_coolsite/coolsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('sondagens.urls')),
    path('sondagens/', include('sondagens.urls')),
    path('admin/', admin.site.urls),
]

02_coolsite/sondagens/urls.py
from django.urls import path

from . import views

app_name = 'sondagens'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalhe'),
    path('<int:pk>/resultados/', views.ResultsView.as_view(), name='resultados'),
    path('<int:question_id>/votar/', views.votar, name='votar'),
]

02_coolsite/sondagens/models.py
import datetime

from django.db import models
from django.utils import timezone


class Questao(models.Model):
    texto = models.CharField(max_length=200)
    data_publicacao = models.DateTimeField('date_published')

    def __str__(self):
        return self.texto

    def foi_publicada_recentemente(self):
        agora = timezone.now()
        return agora - datetime.timedelta(days=1) <= self.data_publicacao <= agora


class Escolha(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto

02_coolsite/sondagens/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Questao, Escolha


class IndexView(generic.ListView):
    template_name = 'sondagens/index.html'
    context_object_name = 'ultimas_questoes'

    def get_queryset(self):
        """ Devolve as últimas 5 questões publicadas"""
        return Questao.objects.order_by('-data_publicacao')[:5]


class DetailView(generic.DetailView):
    model = Questao
    template_name = 'sondagens/detalhe.html'


class ResultsView(generic.DetailView):
    model = Questao
    template_name = 'sondagens/resultados.html'


def votar(request, question_id):
    """ Página que é mostrada ao registar um voto """
    questao = get_object_or_404(Questao, pk=question_id)
    try:
        escolha_selecionada = questao.escolha_set.get(pk=request.POST['escolha'])
    except (KeyError, Escolha.DoesNotExist):
        context = {'questao': questao,
                   'mensagem_de_erro': 'Não selecionou uma questão.'
                   }
        return render(request, 'sondagens/detalhe.html', context)
    else:
        escolha_selecionada.votos = F('votos') + 1
        escolha_selecionada.save()
        return HttpResponseRedirect(reverse('sondagens:resultados',
                                            args=(questao.id,)))

02_coolsite/sondagens/templates/sondagens/detalhe.html
<h1>{{ questao.texto }}</h1>

{% if mensagem_de_erro %}
    <p><strong>{{ mensagem_de_erro }}</strong></p>
{% endif %}

<form action="{% url 'sondagens:votar' questao.id %}" method="post">
    {% csrf_token %}
    {% for escolha in questao.escolha_set.all %}
        <input type="radio" name="escolha" id="escolha{{ forloop.counter }}" value="{{ escolha.id }}">
        <label for="escolha{{ forloop.counter }}">{{ escolha.texto }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="Votar">
</form>

02_coolsite/sondagens/templates/sondagens/index.html
{% if ultimas_questoes %}
    <ul>
    {% for questao in ultimas_questoes %}
            <li><a href="{% url 'sondagens:detalhe' questao.id %}">{{ questao.texto }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não há sondagens para mostrar.</p>
{% endif %}

02_coolsite/sondagens/templates/sondagens/resultados.html
<h1>{{ questao.texto }}</h1>

<ul>
{% for escolha in questao.escolha_set.all %}
    <li>{{ escolha.texto }} -- {{ escolha.votos }} voto{{ escolha.votos|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'sondagens:detalhe' questao.id %}">Votar novamente?</a>